### ISSUE TITLE
Missing assembly Microsoft.TeamFoundation.SourceControl.WebApi

### ISSUE THREAD

**Issue by Cheesebaron** [cake-contrib/Cake.Issues.PullRequests.Tfs#111]
Not sure if this should go here, or in Cake.Tfs.

However, when running `ReportIssuesToPullRequest` on macOS the assembly `Microsoft.TeamFoundation.SourceControl.WebApi` is missing, getting the error:

```
Error: One or more errors occurred.
	Could not load type of field 'Cake.Tfs.PullRequest.TfsPullRequest:pullRequest' (5) due to: Could not load file or assembly 'Microsoft.TeamFoundation.SourceControl.WebApi, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

I have ensured that I have Cake.Tfs as an Addin:

```
#addin nuget:?package=Cake.Tfs&version=0.3.0
#addin nuget:?package=Cake.Issues&version=0.7.0
#addin nuget:?package=Cake.Issues.MsBuild&version=0.7.0
#addin nuget:?package=Cake.Issues.Reporting&version=0.7.0
#addin nuget:?package=Cake.Issues.Reporting.Generic&version=0.7.1
#addin nuget:?package=Cake.Issues.PullRequests&version=0.7.0
#addin nuget:?package=Cake.Issues.PullRequests.Tfs&version=0.7.1
#tool nuget:?package=MSBuild.Extension.Pack&version=1.9.1
```

**Comment by pascalberger** [comment]
This is probably more related to Cake.Tfs, where all the Tfs assemblies are referenced.

What version of Mono do you have installed? We had issues in the past with dependency resolution with version prior to 5.16.x

**Comment by Cheesebaron** [comment]
5.18.1.28

However, not sure where it would find that assembly in the first place. It is not anywhere to find in the tools folder and it is not bundled with mono.
