### ISSUE TITLE
Exception with visualstudio.com URL

### ISSUE THREAD

**Issue by maldworth** [cake-contrib/Cake.Issues.PullRequests.Tfs#56]
Just wanted to say, great work with the Issues. Love it for running my Roslyn Analyzers and automatically commenting on PRs.

I'm following the [sample here](https://cake-contrib.github.io/Cake.Issues.Website/docs/pull-request-systems/tfs/examples/pullrequest-id)

and I notice the url that comes out of it is:
`https://mycompany.visualstudio.com/SomeName/_git/MyRepo`

and this will always fail. I have to add:

`var repoRemoteUrlDefaultCollection = new Uri(repoRemoteUrl.Replace(".visualstudio.com/",".visualstudio.com/DefaultCollection/"));`

then I get
`https://mycompany.visualstudio.com/DefaultCollection/SomeName/_git/MyRepo`

and then it works.

**Comment by pascalberger** [comment]
The underlying TfsUrlParser package seems to have issues with parsing these URLs correctly. I'll therefore transfer this issue to the corresponding project. While not working 100% correct it seems to work for this addin with the new URL schema (`https://MyOrganization@dev.azure.com/MyOrganization/MyProject/_git/MyRepo`).

If you're running your builds in Azure Pipelines you can also read the repository URL from the `BUILD_REPOSITORY_URI` environment variable instead from Git like in this example (but will have the same issues).

I also recently started `Cake.Issues.Recipe` pre-made script providing integration in different build server and pull request systems. You can find its usage [here](https://cake-contrib.github.io/Cake.Issues.Website/docs/usage/recipe/basic-usage). And documentation about supported functionality and tools (currently Azure Pipelines and Azure Repos) [here](https://cake-contrib.github.io/Cake.Issues.Website/docs/recipe/). You can find a Demo project [here](https://dev.azure.com/pberger/_git/Cake.Issues.Recipe-Demo)

**Comment by maldworth** [comment]
I was actually using `SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI` which also has the problem. so I saw your sample, tried switching and had same problem.

Recipe, that looks like a great addition, because there's a decent amount of boilerplate that I needed to add just to get it working. So I will definitely try it out.

You can close this issue if you are going to track the progress through that other issue in the TfsUrlParser.

**Comment by pascalberger** [comment]
@maldworth I'll keep this issue open until the parsing assembly with the fix for parsing visualstudio.com URLs has been updated

**Comment by pascalberger** [comment]
@maldworth Can you please try if using Cake.Tfs 0.2.4-beta.1 solves your problem

**Comment by maldworth** [comment]
@pascalberger Works! Just tested it out using `currentBranch.Remotes`, and also `SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI` by introducing an analyzer error, then correcting it. Thanks

**Comment by pascalberger** [comment]
@maldworth Thanks for reporting back. Cake.Tfs 0.2.4 is now available
